name: inputs-test

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: MOBILE BUILD TYPE
        options: 
        - android
        - ios
        - both
      flavour:
        type: choice
        options:
        - dev
        - cug
        - prod
      
      BUILD_TYPE:
        type: choice
        description: BUILD MODE
        options:
        - debug
        - profile
        - release

      # use-emoji:
      #   type: boolean
      #   description: Include 🎉🤣 emojis
      # environment:
      #   type: environment