name: inputs-test

on:
  workflow_dispatch
    inputs:
      name:
        type: choice
        description: MOBILE BUILD TYPE
        default: 'both'
        options: 
        - android
        - ios
        - both
      flavour:
        required: true
        type: choice
        options:
        - dev
        - cug
        - prod    
      BUILD_TYPE:
        type: choice
        description: BUILD MODE
        required: true
        options:
        - debug
        - profile
        - release
      CHANGE_LOG:
        type: string
        description: "Release Description"
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: list
        run: ls
         

      # use-emoji:
      #   type: boolean
      #   description: Include 🎉🤣 emojis
      # environment:
      #   type: environment