name: Flutter

on:  #events (push and pull_request)
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:   #here we specify the jobs - We could have multiple jobs
  build:  #name it something meaningful 
    runs-on: ubuntu-latest  #runner: select a machine to use

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21 
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
        continue-on-error: true
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get # action

      # - name: Run tests
      #   run: flutter test

      - name: Build android apk and appBundle
        run: |
          flutter build appbundle --release
          ls -R

      # - name: Build android ios
      #   run: |
      #     flutter build ipa --release
      #     ls -R
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: android-app
      #     path: build/app/outputs/flutter-apk/app-release.apk
      - name: secret app id
        run: |
          echo "${{secrets.ANDROID_APP_ID}}" > o.txt
          cat o.txt
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.ANDROID_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.ANDROID_FILE_CONTENT}}
          groups: testers
          file: build/app/outputs/bundle/release/app-release.aab 
    