name: Flutter

on:  #events (push and pull_request)
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:   #here we specify the jobs - We could have multiple jobs
  dependency-setup:  #name it something meaningful 
    runs-on: ubuntu-latest  #runner: select a machine to use

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get # action

  android-build:
    needs: dependency-setup
    runs-on: ubuntu-latest  #runner: select a machine to use
    steps:
      - name: Set up JDK 21 
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
        continue-on-error: true
      - name: Build android apk and appBundle
        run: |
          flutter build appbundle --release
          ls -R
      - uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: build/app/outputs/flutter-apk/app-release.apk
  
  ios-build:
    needs: dependency-setup
    runs-on: ubuntu-latest
    steps:
      - name: Build android ios
          run: |
            flutter build ios --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: build/ios/iphoneos/Runner.ipa
      # - name: Upload artifact to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: "<app_id>"
      #     serviceCredentialsFileContent: ${{secrets.ANDROID_FILE_CONTENT}}
      #     groups: testers
      #     file: build/app/outputs/bundle/release/app-release.aab 


      #     register an app in google play consolse --> firebase --> app
    